// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQss35zR0QBonSiQRDrn13ky_Fv8rf6kQ',
    appId: '1:586224800415:web:251915971b138cb26488aa',
    messagingSenderId: '586224800415',
    projectId: 'iuis-v2',
    authDomain: 'iuis-v2.firebaseapp.com',
    storageBucket: 'iuis-v2.firebasestorage.app',
    measurementId: 'G-C12EEVFGXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoms52jp8k6zn-s5MS5sAD3xyWDHgbEbg',
    appId: '1:586224800415:android:b49f90aad295625f6488aa',
    messagingSenderId: '586224800415',
    projectId: 'iuis-v2',
    storageBucket: 'iuis-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOOIfHsSgQneGt8OfeeHHaaHGjf96FSao',
    appId: '1:586224800415:ios:e7441a6e24e160b86488aa',
    messagingSenderId: '586224800415',
    projectId: 'iuis-v2',
    storageBucket: 'iuis-v2.firebasestorage.app',
    iosBundleId: 'com.example.wvsuIuisV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOOIfHsSgQneGt8OfeeHHaaHGjf96FSao',
    appId: '1:586224800415:ios:e7441a6e24e160b86488aa',
    messagingSenderId: '586224800415',
    projectId: 'iuis-v2',
    storageBucket: 'iuis-v2.firebasestorage.app',
    iosBundleId: 'com.example.wvsuIuisV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQss35zR0QBonSiQRDrn13ky_Fv8rf6kQ',
    appId: '1:586224800415:web:a43bd3b8a4f8a0da6488aa',
    messagingSenderId: '586224800415',
    projectId: 'iuis-v2',
    authDomain: 'iuis-v2.firebaseapp.com',
    storageBucket: 'iuis-v2.firebasestorage.app',
    measurementId: 'G-1LXBBFB4M7',
  );
}
